// @ts-check
import partytown from "@astrojs/partytown";
import react from "@astrojs/react";
import tailwind from "@astrojs/tailwind";
import AstroPWA from "@vite-pwa/astro";
import { defineConfig } from "astro/config";
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const base = "JetLagHideAndSeekZone1LDN";

// Generated by scripts/copy-arcgis-assets.mjs (run via `pnpm dev`/`pnpm build`)
// so @arcgis/core's geodesic engine can be precached and used offline instead
// of being fetched from Esri's CDN.
const arcgisWasmPath = fileURLToPath(
    new URL(
        "./public/arcgis-assets/esri/geometry/support/pe-wasm.wasm",
        import.meta.url,
    ),
);

// The default Workbox globPatterns only picks up common web-asset
// extensions (js/css/html/...), so binary/data files copied into public/
// need to be added explicitly - otherwise they're only cached the first
// time a page fetches them at runtime (via the app's own Cache API calls),
// not precached on install. That's fine for data fetched from Overpass at
// runtime, but anything the app needs to work offline from a cold install
// (no prior visit) has to go in this list.
const precacheDataFile = (relativePath) => {
    const absolutePath = fileURLToPath(
        new URL(`./public/${relativePath}`, import.meta.url),
    );
    return existsSync(absolutePath)
        ? [
              {
                  url: relativePath,
                  revision: createHash("md5")
                      .update(readFileSync(absolutePath))
                      .digest("hex"),
              },
          ]
        : [];
};

const additionalManifestEntries = [
    ...precacheDataFile("arcgis-assets/esri/geometry/support/pe-wasm.wasm"),
    ...precacheDataFile("elevation-london.bin"),
];

/**
 * @param {RegExp} urlPattern
 * @param {string} cacheName
 */
const tileHostCaching = (urlPattern, cacheName) => ({
    urlPattern,
    handler: /** @type {"CacheFirst"} */ ("CacheFirst"),
    options: {
        cacheName,
        expiration: {
            maxEntries: 2000,
            maxAgeSeconds: 60 * 60 * 24 * 30,
        },
        cacheableResponse: {
            statuses: [0, 200],
        },
    },
});

// https://astro.build/config
export default defineConfig({
    integrations: [
        react(),
        tailwind({
            applyBaseStyles: false,
        }),
        partytown({
            config: {
                forward: ["dataLayer.push"],
            },
        }),
        AstroPWA({
            manifest: {
                name: "Jet Lag Hide and Seek Map Generator",
                short_name: "Map Generator",
                description:
                    "Automatically generate maps for Jet Lag The Game: Hide and Seek with ease! Simply name the questions and watch the map eliminate hundreds of possibilities in seconds.",
                icons: [
                    {
                        src: "/JLIcon.png",
                        sizes: "1080x1080",
                        type: "image/png",
                    },
                    {
                        src: "/android-chrome-192x192.png",
                        sizes: "192x192",
                        type: "image/png",
                    },
                    {
                        src: "/android-chrome-512x512.png",
                        sizes: "512x512",
                        type: "image/png",
                    },
                ],
                theme_color: "#1F2F3F",
            },
            workbox: {
                maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
                additionalManifestEntries,
                runtimeCaching: [
                    tileHostCaching(
                        /^https:\/\/[a-z]\.basemaps\.cartocdn\.com\//,
                        "carto-tiles",
                    ),
                    tileHostCaching(
                        /^https:\/\/tile\.openstreetmap\.org\//,
                        "osm-tiles",
                    ),
                    tileHostCaching(
                        /^https:\/\/tile\.thunderforest\.com\//,
                        "thunderforest-tiles",
                    ),
                ],
            },
        }),
    ],
    devToolbar: {
        enabled: false,
    },
    site: "https://amc40.github.io",
    base,
});
