// @ts-check
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import partytown from "@astrojs/partytown";
import react from "@astrojs/react";
import tailwind from "@astrojs/tailwind";
import AstroPWA from "@vite-pwa/astro";
import { defineConfig } from "astro/config";

import { ICON_COLORS } from "./src/maps/api/constants.ts";

const base = "JetLagHideAndSeekZone1LDN";

// The default Workbox globPatterns only picks up common web-asset
// extensions (js/css/html/...), so binary/data files copied into public/
// need to be added explicitly - otherwise they're only cached the first
// time a page fetches them at runtime (via the app's own Cache API calls),
// not precached on install. That's fine for data fetched from Overpass at
// runtime, but anything the app needs to work offline from a cold install
// (no prior visit) has to go in this list - e.g. the arcgis geodesic engine
// WASM (generated by scripts/copy-arcgis-assets.mjs) and the bundled
// elevation grid used offline by the Sea Level Measuring question.
/** @param {string} relativePath */
const precacheDataFile = (relativePath) => {
    const absolutePath = fileURLToPath(
        new URL(`./public/${relativePath}`, import.meta.url),
    );
    return existsSync(absolutePath)
        ? [
              {
                  url: relativePath,
                  revision: createHash("md5")
                      .update(readFileSync(absolutePath))
                      .digest("hex"),
              },
          ]
        : [];
};

const additionalManifestEntries = [
    ...precacheDataFile("arcgis-assets/esri/geometry/support/pe-wasm.wasm"),
    ...precacheDataFile("elevation-london.bin"),
    ...precacheDataFile("coastline50.geojson"),
    ...precacheDataFile("curated-aquariums.geojson"),
    ...precacheDataFile("curated-cinemas.geojson"),
    ...precacheDataFile("curated-consulates.geojson"),
    ...precacheDataFile("curated-highspeed.geojson"),
    ...precacheDataFile("curated-hospitals.geojson"),
    ...precacheDataFile("curated-libraries.geojson"),
    ...precacheDataFile("curated-museums.geojson"),
    ...precacheDataFile("curated-parks.geojson"),
    ...precacheDataFile("curated-stations.geojson"),
    ...precacheDataFile("london-boroughs.geojson"),
    ...precacheDataFile("thames.geojson"),
    // Leaflet marker icons - referenced only via string-built URLs
    // (DraggableMarkers.tsx), so Vite's build never sees an import and the
    // default Workbox globPatterns (js/css/html) never picks up these PNGs.
    // Without this they 404 offline the first time a new question marker
    // (a color the user hasn't dragged yet, so never runtime-cached) is
    // added. Derived from ICON_COLORS so a new color added there is
    // automatically precached too.
    ...Object.keys(ICON_COLORS).flatMap((color) =>
        precacheDataFile(`marker-icon-2x-${color}.png`),
    ),
    ...precacheDataFile("marker-icon-2x.png"),
    ...precacheDataFile("marker-icon.png"),
    ...precacheDataFile("marker-shadow.png"),
];

// Despite the name, this isn't tile-specific - it's a general CacheFirst
// runtime-caching entry for any third-party host whose responses should
// persist for offline use once fetched at least once.
/**
 * @param {RegExp} urlPattern
 * @param {string} cacheName
 */
const tileHostCaching = (urlPattern, cacheName) => ({
    urlPattern,
    handler: /** @type {"CacheFirst"} */ ("CacheFirst"),
    options: {
        cacheName,
        expiration: {
            maxEntries: 2000,
            maxAgeSeconds: 60 * 60 * 24 * 30,
        },
        cacheableResponse: {
            statuses: [0, 200],
        },
    },
});

// https://astro.build/config
export default defineConfig({
    integrations: [
        react(),
        tailwind({
            applyBaseStyles: false,
        }),
        partytown({
            config: {
                forward: ["dataLayer.push"],
            },
        }),
        AstroPWA({
            manifest: {
                name: "Jet Lag Hide and Seek Map Generator",
                short_name: "Map Generator",
                description:
                    "Automatically generate maps for Jet Lag The Game: Hide and Seek with ease! Simply name the questions and watch the map eliminate hundreds of possibilities in seconds.",
                icons: [
                    {
                        src: "/JLIcon.png",
                        sizes: "1080x1080",
                        type: "image/png",
                    },
                    {
                        src: "/android-chrome-192x192.png",
                        sizes: "192x192",
                        type: "image/png",
                    },
                    {
                        src: "/android-chrome-512x512.png",
                        sizes: "512x512",
                        type: "image/png",
                    },
                ],
                theme_color: "#1F2F3F",
            },
            workbox: {
                maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
                additionalManifestEntries,
                runtimeCaching: [
                    tileHostCaching(
                        /^https:\/\/[a-z]\.basemaps\.cartocdn\.com\//,
                        "carto-tiles",
                    ),
                    tileHostCaching(
                        /^https:\/\/tile\.openstreetmap\.org\//,
                        "osm-tiles",
                    ),
                    tileHostCaching(
                        /^https:\/\/tile\.thunderforest\.com\//,
                        "thunderforest-tiles",
                    ),
                    tileHostCaching(
                        /^https:\/\/fonts\.googleapis\.com\//,
                        "google-fonts-stylesheets",
                    ),
                    tileHostCaching(
                        /^https:\/\/fonts\.gstatic\.com\//,
                        "google-fonts-webfonts",
                    ),
                ],
            },
        }),
    ],
    devToolbar: {
        enabled: false,
    },
    site: "https://amc40.github.io",
    base,
});
